#!/bin/bash
if [ -n "$1" ]
then

#Create dir for our file
mkdir -p ~/laba3image

#Create file for image configurate 
touch ~/laba3image/Dockerfile

#Setup file
echo 'FROM vulnerables/web-dvwa' > ~/laba3image/Dockerfile
echo 'RUN touch /etc/mysecret' >> ~/laba3image/Dockerfile
echo 'RUN echo ' $1 ' > /etc/mysecret' >> ~/laba3image/Dockerfile
echo 'EXPOSE 80' >> ~/laba3image/Dockerfile

docker build -t laba3image/web-dvwa ~/laba3image

rm -rf ~/laba3image

else
echo "No parameters found. "
fi
